# Generated by Django 2.0.13 on 2019-05-20 17:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bboard', '0003_bb_kind'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bb',
            name='kind',
            field=models.CharField(blank=True, choices=[('s', 'Продам'), ('b', 'Куплю'), (None, 'Выберите действие'), ('c', 'Обменяю')], db_index=True, max_length=1, verbose_name='Действие'),
        ),
    ]
