# Generated by Django 2.0.13 on 2019-05-20 18:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bboard', '0004_auto_20190520_2044'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bb',
            name='kind',
        ),
    ]
