# Generated by Django 2.0.13 on 2019-05-22 16:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bboard', '0006_bb_kind'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bb',
            name='kind',
            field=models.CharField(blank=True, choices=[('Куплю', 'Куплю'), ('Продам', 'Продам'), ('Обменяю', 'Обменяю')], max_length=10, verbose_name='Действие'),
        ),
    ]
