# Generated by Django 2.0.13 on 2019-06-18 10:34

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bboard', '0008_auto_20190607_1937'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bb',
            name='content',
            field=models.TextField(blank=True, error_messages={'unique': 'Такое описание уже используется'}, null=True, unique=True, verbose_name='Описание'),
        ),
        migrations.AlterField(
            model_name='bb',
            name='price',
            field=models.FloatField(blank=True, error_messages={'max_value': 'Слишком большая цена'}, null=True, validators=[django.core.validators.MaxValueValidator(9999999)], verbose_name='Цена'),
        ),
        migrations.AlterField(
            model_name='bb',
            name='title',
            field=models.CharField(max_length=50, validators=[django.core.validators.MinLengthValidator(2, message='Слишком маленькое название')], verbose_name='Товар'),
        ),
    ]
